# Generated by Django 6.1.1 on 2026-09-02 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(default='bubblegum_pop', max_length=64)),
                ('audio_output_device', models.CharField(blank=True, max_length=255, null=True)),
                ('master_volume', models.IntegerField(default=80)),
                ('autoscan_on_start', models.BooleanField(default=False)),
                ('midi_init_mode', models.CharField(default='gm', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=500)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('artist', models.CharField(blank=True, max_length=255, null=True)),
                ('genre', models.CharField(blank=True, max_length=255, null=True)),
                ('collection', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.CharField(blank=True, max_length=32, null=True)),
                ('bpm', models.IntegerField(blank=True, null=True)),
                ('key', models.CharField(blank=True, max_length=16, null=True)),
                ('time_sig', models.CharField(blank=True, max_length=16, null=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('is_favorite', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('lyrics_filename', models.CharField(blank=True, max_length=500, null=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('missing', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.playlist')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.song')),
            ],
            options={
                'unique_together': {('playlist', 'song')},
            },
        ),
        migrations.AddField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(related_name='playlists', through='app.PlaylistSong', to='app.song'),
        ),
        migrations.AddField(
            model_name='song',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs', to='app.source'),
        ),
    ]
