# Generated by Django 6.1.1 on 2026-09-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='backend',
            field=models.CharField(default='fluidsynth', max_length=16),
        ),
        migrations.AddField(
            model_name='settings',
            name='export_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='start_fullscreen',
            field=models.BooleanField(default=False),
        ),
    ]
