# Generated by Django 6.1.1 on 2026-09-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_settings_backend_settings_export_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
